### ISSUE TITLE
Not working for me. Still taking space in my Google account

### ISSUE THREAD

**Issue by lihanchen** [mehedihjoy0/GPhotos-Unlimited#1]
I have Magisk 28 + GPhotos Unlimited 2.0 + Google Photo 7.4.0.687342855
I install magisk + module and reboot first and then download Google Photo from Play Store.
The Google Photo experience is just like if there were no plug in. The storage page shows the 100GB trial.
I don't know if I am supposed to see something like "Pixel user got unlimited storage"

I tried to take a video and upload, it occupies space in my Google account

**Comment by mehedihjoy0** [comment]
Reflash the module and reboot. Don't try to install from Google Play Store. It will automatically be installed by itself.
