### ISSUE TITLE
Why you dont mount apk file as yt revanced ?

### ISSUE THREAD

**Issue by NCLnclNCL** [mehedihjoy0/GPhotos-Unlimited#4]
Need only 2 line for it
bind_apk com.google.android.apps.photos Photos.apk
am force-stop com.google.android.apps.photos

**Comment by mehedihjoy0** [comment]
I included an auto installer. This module checks the version of the installed "Google Photos" on every reboot. If version mismatches, the module uninstalls and installs itself automatically.
